config/routes.rb
BlacklightEds::Engine.routes.draw do
  # EDS
  get 'articles', to: 'articles#index', as: :eds_articles
  get 'all', to: 'articles#all', as: :eds_all
  get 'articles/:dbid/:an', to: 'articles#show', :constraints  => { :an => /[^\/]+/ }, as: :eds_detail
  get 'articles/:dbid/:an/fulltext/:fulltext_type', to: 'articles#fulltext', :constraints  => { :an => /[^\/]+/ }, as: :eds_fulltext
  get 'articles/switch/', to: 'articles#switch', as: :eds_switch
  get 'articles/advanced', to: 'articles#advanced', as: :eds_articles_advanced
end

app/controllers/blacklight_eds/application_controller.rb
module BlacklightEds
  class ApplicationController < ::ApplicationController
    include BlacklightEds::ArticlesControllerBehavior
    include BlacklightEds::ArticlesSearchContext
    include BlacklightEds::ArticlesUrlBehavior

  end
end

app/controllers/blacklight_eds/articles_controller.rb
require 'ebsco-discovery-service-api'
require_dependency "blacklight_eds/application_controller"

class BlacklightEds::ArticlesController < BlacklightEds::ApplicationController
  include Blacklight::Catalog
  include Blacklight::Marc::Catalog
  include BlacklightEds::Articles
  #include Blacklight::Catalog::SearchContext

  copy_blacklight_config_from CatalogController

  helper_method :search_action_url
  helper_method :path_for_eds_article

  before_action :current_search_session, only: [:all, :index, :advanced]

  # to override any method in this class, create a new module, and include it in the extended controller class
end

app/controllers/concerns/blacklight_eds/articles_search_context.rb
module BlacklightEds::ArticlesSearchContext
  extend ActiveSupport::Concern

  included do
    helper_method :eds_session
  end

  def eds_session
    # prevent eds_session[:info] from overloading the session by removing it
    if session[:eds].nil?
    else
      session[:eds].delete :info
    end
    session[:eds] ||= {}
  end
end

app/controllers/concerns/blacklight_eds/articles_url_behavior.rb
module BlacklightEds::ArticlesUrlBehavior
  extend ActiveSupport::Concern

  included do
    helper_method :path_for_eds_article
  end

  def path_for_eds_article(*args)
    eds_detail_path *args
  end
end

app/helpers/blacklight_eds/application_helper.rb
module BlacklightEds
  module ApplicationHelper

    include CrudLinksHelper

    # The layout file from the main app might invoke
    # some of the named routes from blacklight, which
    # causes errors on the blacklight_folders views
    # unless you add the main_app prefix.
    def method_missing(method, *args)
      if main_app_url_helper?(method)
        main_app.send(method, *args)
      else
        super
      end
    end

    private

    def main_app_url_helper?(method)
      method.to_s.end_with?('_path', '_url') && main_app.respond_to?(method)
    end

  end
end

app/helpers/blacklight_eds/blacklight_eds_helper.rb
require 'htmlentities'
require 'addressable/uri'
require 'ipaddr'

module BlacklightEds::BlacklightEdsHelper

  # check to see if result has any facets.  crude, and I forget why I had to do a length check..
  def has_eds_facets?
    @results.fetch('SearchResult', {}).fetch('AvailableFacets', []).any?
  end

  # pulls <QueryString> from the results of the current search to serve as the baseURL for next request
  def generate_next_url
    if eds_session.has_key? :query_string
      url = HTMLEntities.new.decode eds_session[:query_string]

      #blacklight expects the search term to be in the parameter 'q'.
      #q is moved back to 'query-1' in 'generate_api_query'
      #should probably pull from Info method to determine replacement strings
      #i could turn the query into a Hash, but available functions to do so delete duplicated params (Addressable)
      # url.gsub!("query-1=AND,TI:", "q=")
      # url.gsub!("query-1=AND,AU:", "q=")
      # url.gsub!("query-1=AND,SU:", "q=")
      # url.gsub!("query-1=AND,", "q=")

      #Rails framework doesn't allow repeated params.  turning these into arrays fixes it.
      url.gsub!("facetfilter=", "facetfilter[]=")
      url.gsub!("limiter=", "limiter[]=")

      #i should probably pull this from the query, not the URL
      if (params[:search_field]).present?
        url << "&search_field=" << params[:search_field].to_s
      end
      return url
    else
      return ''
    end
  end

  # Returns URL with appened eds_action
  def eds_action_url eds_action
    search_action_url + '?' + generate_next_url + '&eds_action=' + eds_action
  end

  #for the search form at the top of results
  #retains some of current search's fields (limiters)
  #discards pagenumber, facets and filters, actions, etc.
  def show_hidden_field_tags
    hidden_fields = ''
    options = params.except(:search_field, :fromDetail, :facetfilter, :pagenumber, :q, :dbid, :an, :fulltext_type, :highlight, :resultId, :utf8)
    options.each do |key, value|
      if key == 'eds_action'
        if value =~ /addlimiter/ or value =~ /removelimiter/ or value =~ /setsort/ or value =~ /SetResultsPerPage/
          hidden_fields << '<input type="hidden" name="' << key.to_s << '" value="' << value.to_s << '" />'
        end
      elsif value.kind_of?(Array)
        value.each do |v|
          hidden_fields << '<input type="hidden" name="' << key.to_s << '[]" value="' << v.to_s << '" />'
        end
      else
        hidden_fields << '<input type="hidden" name="' << key.to_s << '" value="' << value.to_s << '" />'
      end
    end
    hidden_fields.html_safe
  end

  #############
  # Facets / Limiters sidebar
  #############

  def show_limiter_checkbox limiter, count
    applied_limiter = @results.fetch('SearchRequestGet', {}).fetch('SearchCriteriaWithActions', {}).
        fetch('LimitersWithAction', []).find { |applied_limiter|
      applied_limiter["Id"] == limiter["Id"]
    }
    limiter_checked = applied_limiter.present?
    limiter_action = limiter_checked ? applied_limiter["RemoveAction"].to_s : limiter["AddAction"].to_s.gsub('value', 'y')

    clickURL = eds_action_url limiter_action
    clickaction = "window.location.assign('" + clickURL + "');"

    check_box_tag("limiters", limiter_action, limiter_checked, :id => ("limiter-" + count.to_s), :style => "margin-top:-5px;", :onclick => clickaction)
  end

  def show_date_link prior
    current_year = Time.new.year
    url = eds_action_url "addlimiter(DT1:#{(current_year - prior).to_s}-01/#{current_year.to_s}-12)"
    link_to "Last #{prior} Years", url
  end

  #############
  # Sort / Display / Record Count
  #############

  # pull sort options from INFO method
  def show_sort_options
    sortDropdown = ""
    eds_info.fetch('AvailableSearchCriteria', {}).fetch('AvailableSorts', []).each do |sort_option|
      sortDropdown << "<li><a href='#{eds_action_url sort_option["AddAction"].to_s}'>#{sort_option["Label"].to_s}</a></li>"
    end
    sortDropdown.html_safe
  end

  # shows currently selected view
  def show_view_option
    uri = Addressable::URI.parse(request.fullpath.split("?")[0] + "?" + generate_next_url)
    newUri = uri.query_values
    if newUri['view'].present?
      view_option = newUri['view'].to_s
    else
      view_option = "detailed"
    end
    return view_option
  end

  # shows currently selected sort
  def show_current_sort
    current_sort = params[:eds_action].present? ? params[:eds_action].gsub("setsort(", "").gsub(")", "") : nil
    current_sort = params[:sort].present? ? params[:sort] : nil if current_sort.nil?

    sort_option = eds_info.fetch('AvailableSearchCriteria', {}).fetch('AvailableSorts', []).find { |sort_option|
      sort_option['Id'].to_s == current_sort
    }
    sort = sort_option.present? ? sort_option['Label'] : 'Relevance'
    "Sort by #{sort}"
  end


  #############
  # Facet / Limiter Constraints Box
  #############

  # used when determining if the "constraints" partial should display
  def query_has_facetfilters?(localized_params = params)
    (generate_next_url.scan("facetfilter[]=").length > 0) or (generate_next_url.scan("limiter[]=").length > 0) or
        (generate_next_url.scan("q=").length > 0) or (params[:advanced] == 'true') or (generate_next_url.scan("query-").length > 0)
  end

  def list_applied_queries
    field_codes = {TI: 'Title', TX: 'All Text', SU: 'Subject', SO: 'Journal', AB: 'Abstract', AU: 'Author', DT: 'Date'}
    applied_queries = []
    qwa = @results.fetch('SearchRequestGet', {}).fetch('SearchCriteriaWithActions', {}).
        fetch('QueriesWithAction', [])
    if not qwa.nil?
      qwa.each_with_index do |query, index|
        options = {
            class: "query-constraint",
            remove_action: query.fetch('RemoveAction', ''),
            filter_value: query['Query']['Term'],
            filter_name: query['Query']['FieldCode'] || 'keyword'
        }

        if query['Query']['FieldCode']
          options[:filter_name] = field_codes.fetch(query['Query']['FieldCode'].to_sym, query['Query']['FieldCode'])
        else
          options[:filter_name] = 'keyword'
        end

        if options[:filter_name] == 'Date'
          dates = options[:filter_value].split('-')
          options[:filter_value] = "#{dates[0][4..5]}/#{dates[0][0..3]}-#{dates[1][4..5]}/#{dates[1][0..3]}"
        end

        applied_queries << options
      end
    end
    applied_queries
  end

  def list_applied_facets
    applied_facets = []
    @results.fetch('SearchRequestGet', {}).fetch('SearchCriteriaWithActions', {}).
        fetch('FacetFiltersWithAction', []).each do |applied_facet|
      applied_facet['FacetValuesWithAction'].each do |facet_value|
        options = {
            class: "filter-#{facet_value['FacetValue']['Id'].to_s.gsub('EDS', '').gsub(' ', '').titleize}",
            remove_action: facet_value['RemoveAction'].to_s.gsub('&', '%26'),
            filter_name: facet_value['FacetValue']['Id'].to_s.gsub("EDS", "").titleize,
            filter_value: facet_value['FacetValue']['Value'].to_s.titleize
        }
        applied_facets << options
      end
    end
    applied_facets
  end

  def list_applied_limiters
    applied_limiters = []
    @results.fetch('SearchRequestGet', {}).fetch('SearchCriteriaWithActions', {}).
        fetch('LimitersWithAction', []).each do |applied_limiter|
      limiter = eds_info.fetch('AvailableSearchCriteria', {}).fetch('AvailableLimiters', []).find { |limiter|
        limiter["Id"] == applied_limiter["Id"]
      }
      limiter_label = limiter.present? ? limiter["Label"] : 'No Label'
      options = {
          class: "filter-#{applied_limiter["Id"]}",
          remove_action: applied_limiter["RemoveAction"]
      }

      if applied_limiter["Id"] == "DT1"
        applied_limiter["LimiterValuesWithAction"].each do |limiter_values|
          options[:filter_name] = limiter_label.to_s.titleize
          options[:filter_value] = limiter_values["Value"].gsub("-01/", " to ").gsub("-12", "")
          applied_limiters << options
        end
      else
        options.delete :filter_name
        options[:filter_value] = limiter_label.to_s.titleize
        applied_limiters << options
      end
    end
    applied_limiters
  end

  ###########
  # Pagination
  ###########

  #display how many results are being shown
  def show_results_per_page
    if params[:eds_action].present?
      if params[:eds_action].to_s.scan(/SetResultsPerPage/).length > 0
        rpp = params[:eds_action].to_s.gsub("SetResultsPerPage(", "").gsub(")", "").to_i
        return rpp
      end
    end
    if params[:resultsperpage].present?
      return params[:resultsperpage].to_i
    end
    return 20
  end

  #calculates total number of pages in results set
  def show_total_pages
    pages = show_total_hits / show_results_per_page
    return pages + 1
  end

  #get current page, which serves as a base for most pagination functions
  def show_current_page
    if params[:eds_action].present?
      if params[:eds_action].scan(/GoToPage/).length > 0
        pagenum = params[:eds_action].to_s
        newpagenum = pagenum.gsub("GoToPage(", "")
        newpagenum = newpagenum.gsub(")", "")
        return newpagenum.to_i
      elsif params[:eds_action].scan(/SetResultsPerPage/).length > 0
        if params[:pagenumber].present?
          return params[:pagenumber].to_i
        else
          return 1
        end
      else
        return 1
      end
    end
    if params[:pagenumber].present?
      return params[:pagenumber].to_i
    end
    return 1
  end

  #display pagination at the top of the results list
  def show_compact_pagination
    previous_link = ''
    next_link = ''
    first_result_on_page_num = ((show_current_page - 1) * show_results_per_page) + 1
    last_result_on_page_num = first_result_on_page_num + show_results_per_page - 1
    if last_result_on_page_num > show_total_hits
      last_result_on_page_num = show_total_hits
    end

app/helpers/blacklight_eds/blacklight_eds_url_helper.rb
module BlacklightEds::BlacklightEdsUrlHelper
  
end

app/helpers/blacklight_eds/crud_links_helper.rb
module BlacklightEds
  module CrudLinksHelper
    def action_label model, action=nil
      action_default_value model, action
    end

    private
    def action_default_value object, key = nil
      object_model = convert_to_model(object)

      key ||= object_model ? (object_model.persisted? ? :edit : :create) : :view

      case object_model
      when Symbol, String
        model = object_model
        object_name = object_model
      else
        model = object_model.class.model_name.human
        object_name = object_model.class.model_name.i18n_key
      end

      defaults = []
      defaults << :"helpers.action.#{object_name}.#{key}"
      defaults << :"helpers.action.#{key}"
      defaults << "#{key.to_s.humanize} #{model}"
      I18n.t(defaults.shift, model: model, default: defaults)
    end
  end
end

app/views/blacklight_eds/articles/_advanced_form.html.erb
<h1 class="advanced page-header">
  Articles Advanced Search
</h1>
<%= form_tag(eds_articles_path, method: :get, class: 'form-horizontal advanced') do %>
    <input name="utf8" type="hidden" value="✓">
    <%= hidden_field_tag 'advanced', 'true' %>

    <div id="advanced_search">
      <div class="form-group advanced-search-field">
        <label class="col-sm-3 control-label" for="alltext">All Fields</label>
        <div class="col-sm-9">
          <input class="form-control" name="alltext" type="text">
        </div>
      </div>
      <div class="form-group advanced-search-field">
        <label class="col-sm-3 control-label" for="title">Title</label>
        <div class="col-sm-9">
          <input class="form-control" id="title" name="title" type="text">
        </div>
      </div>
      <div class="form-group advanced-search-field">
        <label class="col-sm-3 control-label" for="author">Author</label>
        <div class="col-sm-9">
          <input class="form-control" id="author" name="author" type="text">
        </div>
      </div>
      <div class="form-group advanced-search-field">
        <label class="col-sm-3 control-label" for="journal">Journal Title</label>
        <div class="col-sm-9">
          <input class="form-control" id="journal" name="journal" type="text"/>
        </div>
      </div>

      <div class="form-group advanced-search-field">
        <label class="col-sm-3 control-label">Published</label>
        <div class="col-sm-9">
          <label class="col-sm-2 control-label" for="publication_date_start">Start</label>
          <input class="col-sm-4" name="publication_date_start" type="text" placeholder="MM/YYYY"/>
          <label class="col-sm-2 control-label" for="publication_date_start">End</label>
          <input class="col-sm-4" name="publication_date_end" type="text" placeholder="MM/YYYY"/>
        </div>
      </div>

      <div class="sort-submit-buttons clearfix" class="col-sm-12">
        <div class="sort-buttons pull-left">
          <label class="control-label" for="sort">Sort results by</label>
          <div class="sort-option-advanced">
          <select class="form-control sort-select" id="sort" name="sort">
            <option value="date">Date Newest</option>
            <option value="date2">Date Oldest</option>
            <option value="author">Author</option>
            <option value="relevance" selected>Relevance</option>
          </select>
          </div>
        </div>

        <div class="submit-buttons pull-right">
          <%= link_to 'Start Over', eds_articles_advanced_path, html_options={class: 'btn btn-default advanced-search-start-over'} %>
          <input class="btn btn-primary advanced-search-submit" id="advanced-search-submit" name="commit" type="submit" value="Search">
        </div>
      </div>
    </div>


<%- end %>

app/views/blacklight_eds/articles/_constraints_element.html.erb
<span class="btn-group appliedFilter constraint filter <%= options[:class] %>">
  <a class="constraint-value btn btn-sm btn-default btn-disabled" href="<%= eds_action_url options[:remove_action] %>">
    <%- if options.has_key? :filter_name %>
        <span class="filterName"><%= options[:filter_name] %></span>
    <%- end %>
    <span class="filterValue"><%= options[:filter_value] %></span>
  </a>
  <a class="btn btn-default btn-sm remove dropdown-toggle" href="<%= eds_action_url options[:remove_action] %>">
    <span class="glyphicon glyphicon-remove"></span>
    <span class="sr-only">Remove filter <%= options[:filter_name] + ':' if options.has_key? :filter_name %> <%= options[:filter_value] %></span>
  </a>
</span>

app/views/blacklight_eds/articles/_document_list.html.erb
<% # container for all documents in index view -%>
<%- if eds_has_search_parameters? %>
    <%- if has_records? @results %>
        <div id="documents">
          <% @results['SearchResult']['Data']['Records'].each do |result| %>
              <%= render 'document', result: result %>
          <% end %>
        </div>
    <%- end %>
<%- else %>
    <p>Empty Search.</p>
<%- end %>

app/views/blacklight_eds/articles/_facet_limit.html.erb
<ul class="facet-values list-unstyled">
  <%- facet.fetch('AvailableFacetValues', []).each do |facetValue|%>
      <li>
        <span class="facet-label">
          <a class="facet_select" href="<%=request.fullpath.split("?")[0] + "?" + generate_next_url + "&eds_action=" + CGI.escape(facetValue['AddAction'].to_s)%>">
            <%=facetValue['Value'].to_s.titleize%>
          </a>
        </span>
        <span class="facet-count">
          <%= number_with_delimiter(facetValue['Count']) %>
        </span>
      </li>
  <%- end %>
</ul>

app/views/blacklight_eds/articles/_facet_limiters.html.erb
<div class="panel panel-default facet_limit blacklight-Limiters">
  <div class="collapse-toggle panel-heading" data-target="#facet-Limiters" data-toggle="collapse">
    <h5 class="panel-title"><a href="#" data-no-turbolink="true">Search Options</a></h5>
  </div>
  <div id="facet-Limiters" class="panel-collapse facet-content collapse in" style="height: auto;">
    <div class="panel-body">
      <form class="form">
        <ul class="facet-values list-unstyled">
          <%- eds_info.fetch('AvailableSearchCriteria', {}).fetch('AvailableLimiters', []).select {|l| l['Type'] == 'select'}.each_with_index do |limiter, count| %>
              <li style='font-size:small;'>
                <%= show_limiter_checkbox limiter, count %>
                <%= limiter['Label'] %>
              </li>
          <%- end %>
        </ul>
      </form>
    </div>
  </div>
</div>

app/views/blacklight_eds/articles/_home_text.html.erb
<h4><%= t('blacklight.welcome') %></h4>
<p>&nbsp;</p>
<p>The articles section of Blacklight searches through the university's collection of journals, newspapers, magazines, etc.  This space could be filled by a brief introductory video, links to library resources and guides, or whatever!</p>
<p>You can also customize the "<a href="/articles?q=evil+atomizer">No Results</a>" screen, which is a great point-of-need for struggling researchers.</p>
<% #Creates a bit space in the page -%>

app/views/blacklight_eds/articles/_previous_next_doc.html.erb
<%#Using the Bootstrap Pagination class  -%>
<div class="well" id="previousNextDocument">
  <% if params[:resultId].present? and eds_session[:results].present? %>
      <% if params[:resultId] != "1" %>
          <% prevId = params[:resultId].to_i - 1 %>
          <%= link_to "Previous", request.fullpath.split("/" + params[:dbid])[0] + "/switch/?" + generate_next_url + "&resultId=" + prevId.to_s %>
          |
      <% end %>
      Result <strong><%= params[:resultId].to_s %></strong> of <strong><%= number_with_delimiter(show_total_hits) %></strong>
      <% if params[:resultId].to_i < show_total_hits.to_i %>
          <% nextId = params[:resultId].to_i + 1 %>
          | <%= link_to "Next", request.fullpath.split("/" + params[:dbid])[0] + "/switch/?" + generate_next_url + "&resultId=" + nextId.to_s %>
      <% end %>
  <% end %>

  <div class="pull-right">
    <% if params[:resultId].present? and eds_session[:results].present? %>
        <%= link_to "Back to Search Results", request.fullpath.split("/" + params[:dbid])[0] + "?" + generate_next_url + "&fromDetail=y" %>
        |
    <% end %>
    <%= link_to 'New Search', search_action_url %>
  </div>
</div>

app/views/blacklight_eds/articles/_show_more_like_this.html.erb
<li class="more_like_this_document">
  <span class="mlt_title"><%= link_to_document document, :label=>document_show_link_field %></span>
</li>

app/views/blacklight_eds/articles/_show_sidebar.html.erb
<div class="well" id="sidebar-nav">
  <%= render :partial => 'show_tools' %>
</div><!--/well -->
  
<% unless @document.more_like_this.empty? %>
<div class="well" id="sidebar-mlt">
  <ul class="nav nav-list">
  <li class="nav-header">More Like This</li>
    <%= render :collection => @document.more_like_this, :partial => 'show_more_like_this', :as => :document %>
  </ul>
</div><!--/well -->
<% end %>

app/views/blacklight_eds/articles/_sort_and_per_page.html.erb
<% if @results['SearchResult']['Data']['Records'].present? %>
<div id="sortAndPerPage" class="clearfix">
   <div class="page_links">
     <%= render :partial => "paginate_compact" %>
   </div>
   <div class="search-widgets pull-right">

    <%= render :partial => 'view_options_widget' %>
    <%= render :partial => 'per_page_widget' %>
    <%= render :partial => 'sort_widget' %>

   </div>
</div>
<% else %>
<div id="sortAndPerPage">
   <div class="page_links">
     <table border="0">
      <tr>
         <td>
            <h4>No search results.</h4><p>Need help?  Don't hesitate to contact your local reference librarian today, or try on of these useful guides:
            <ul>
               <li><a href="#">Library Research Guide #1</a></li>
               <li><a href="#">Library Research Guide #2</a></li>
               <li><a href="#">Library Research Guide #3</a></li>
            </ul>
            </p>
         </td>
         <td>
            <iframe width="420" height="315" src="http://www.youtube.com/embed/r_eGdSp47Uw" frameborder="0" allowfullscreen></iframe>
         </td>
      </tr>
     </table>
     </div>
</div>   
<% end %>

app/views/blacklight_eds/articles/advanced.html.erb
<div id="content" class="col-md-12">
  <div class="col-md-3 col-sm-4"></div>
  <div class="col-md-9 col-sm-8">
    <%= render 'blacklight_eds/articles/advanced_form' %>
  </div>
</div>

app/views/blacklight_eds/articles/citation.html.erb
<%= render :partial => 'citation' -%>

app/views/blacklight_eds/articles/citation.js.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3><%= t('blacklight.tools.cite') %></h3>
</div>
<div class="modal-body">
<%= render :partial => 'citation' -%>
</div>

app/views/blacklight_eds/articles/show.html.erb
<% require 'sanitize' %>

<% if has_restricted_access?(@record) %>
    <meta http-equiv="REFRESH" content="0;url=<%= new_user_session_path %>" />
<% else %>

    <div class="row">

      <div id="content" class="span9 show-document">

        <%= render 'previous_next_doc' %>

        <% @page_title = Sanitize.clean(show_title(@record)) << " - Detailed @record - Blacklight" %>

        <%# this should be in a partial -%>
        <div id="document" class="articles<%# TODO: FIX render_document_class %>">
          <div id="doc_<%= params[:dbid] %>_<%= params[:an] %>">


            <%# bookmark/folder functions -%>
            <h1><%= show_title(@record) %></h1>

            <div class="document">
              <dl class="dl-horizontal dl-invert">

                <% if has_authors?(@record) %>
                    <dt class="blacklight-author_display">Author:</dt>
                    <dd class="blacklight-author_display"><%= show_authors(@record) %></dd>
                <% end %>

                <% if has_titlesource?(@record) %>
                    <dt class="blacklight-author_display">Source:</dt>
                    <dd class="blacklight-author_display"><%= show_titlesource(@record) %></dd>
                <% elsif has_pubdate?(@record) %>
                    <dt class="blacklight-format">Published:</dt>
                    <dd class="blacklight-format"><%= show_pubdate(@record) %></dd>
                <% end %>

                <% if has_pubtype?(@record) %>
                    <dt class="blacklight-format">Format:</dt>
                    <dd class="blacklight-format"><%= show_pubtype(@record) %></dd>
                <% end %>

                <% if has_abstract?(@record) %>
                    <dt class="blacklight-abstract">Abstract:</dt>
                    <dd class="blacklight-abstract"><%= show_abstract(@record) %></dd>
                <% end %>

                <% if has_subjects?(@record) %>
                    <dt class="blacklight-subject">Subjects:</dt>
                    <dd class="blacklight-abstract"><%= show_subjects(@record) %></dd>
                <% end %>

                <% if has_full_text_on_screen?(@record) %>
                    <a name="fulltext"></a>
                    <dt class="blacklight-subject">Full Text:</dt>
                    <% if eds_user_signed_in? or ip_in_range? %>
                        <dd class="blacklight-abstract"><%= show_full_text_on_screen(@record).html_safe %></dd>
                    <% else %>
                        <dd class="blacklight-abstract"><%= link_to "Please log in to display full-text.", new_user_session_path %></dd>
                    <% end %>
                <% end %>

              </dl>
            </div>
          </div>
        </div>
      </div>

      <div id="sidebar" class="span3">
        <div class="@record-image-detail">
          <% if has_coverimage?(@record) %>
              <img src="<%= show_coverimage_link(@record) %>" border="0" />
          <% else %>
              <span class="pt-icon pt-<%= show_pubtypeid(@record) %>"></span>
          <% end %>
          <br />
          <%= show_pubtype(@record) %>
        </div>
        <% if eds_user_signed_in? or ip_in_range %>
            <%= render partial: 'fulltext_links', locals: { delimiter: '<br/>'.html_safe, record: @record } %>
        <% else %>
            <dt class="blacklight-fulltext"><%= link_to "Please log in to see full-text options", new_user_session_path %></dt>
        <% end %>

        <br />
        <dt class="blacklight-fulltext">Other Options:</dt>
        <dd class="blacklight-fulltext"><%= link_to("View record in EDS", show_plink(@record),:target => "_blank") %></dd>

      </div><!--/span -->
    </div>
<% end %>
<%# render :partial => 'debug' %>